### ISSUE TITLE
Add rollup for bundling and code compression.

### ISSUE THREAD

**Issue by KargJonas** [cjss-group/CJSS#22]
Is it time to add a build step?

**Comment by KargJonas** [comment]
This would be sort of necessary anyways if we plan to implement plugins #14

**Comment by xsanda** [comment]
@scottkellum What's the correct way of doing this to avoid having the built version lying around in repo, possibly getting out of sync? Would it be with something like [Travis releases](https://docs.travis-ci.com/user/deployment/releases/)?

**Comment by KargJonas** [comment]
#29
