### ISSUE TITLE
Allow for expansion regardless of order

### ISSUE THREAD

**Issue by xsanda** [cjss-group/CJSS#27]
At the moment, CSS rules are evaluated strictly in the order they appear in the source code. This makes ordering the CSS a challenge. In addition, it prevents any sort of recursion.

I would propose parsing all the CSS rules, then evaluating each of them, marking each element as having completed each rule internally. The rules are iterated, and whenever `--body` is evaluated, all the rules (up to and including the currently processed rule) are run on its child structure recursively too.

**Comment by xsanda** [comment]
With #37 this should be an extremely easy refactor.

**Comment by xsanda** [comment]
@KargJonas should `script {}` rules be executed first or last?

**Comment by KargJonas** [comment]
Hmm.. Good question. Maybe we need lifecycle methods or events so the user can decide.
